# Generated by Django 3.2.7 on 2021-09-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210927_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=100, null=True),
        ),
    ]
